
AMQP_URI: ${QUEUE_HOST}
WEB_SERVER_ADDRESS: '0.0.0.0:5000'
max_workers: 10
parent_calls_tracked: 10

DB_URIS:
    "command_stack:Base": ${COMMANDDB_HOST}
    "events:Base": ${COMMANDDB_HOST}

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]